version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: app/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
      - ./db:/app/db
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development